### ISSUE TITLE
macro is not triggering

### ISSUE THREAD

**Issue by ve3k** [yaorenmao/macro-maker#2]
macro is configured, but nothing happens after pressing triggering skill

```
	"rmyst": [
		[
			"231100",
			"test1",
			"0",
			0,
			"0",
			"81100",
			"1500"
		]
	],
```

![mm](https://user-images.githubusercontent.com/22611275/51387291-ce46d800-1b25-11e9-8c2b-fb05b0b6b0a1.PNG)
delay should be fine as well
![mm2](https://user-images.githubusercontent.com/22611275/51387422-444b3f00-1b26-11e9-880f-403d8766ee58.PNG)

**Comment by yaorenmao** [comment]
Macro isn't working for Targeted and Lock-on skills, bugged with range skills(projectiles always target same side).

**Comment by ve3k** [comment]
I used "metamorphic smite" and metamorphic blast" for test.
Either of skills is targeted or lockon or projectile.
